services:
  api:
    build: ./apps/api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/stepexplorer
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - stepexplorer

  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - stepexplorer

  postgres:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stepexplorer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - stepexplorer

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - stepexplorer

volumes:
  postgres_data:
  redis_data:

networks:
  stepexplorer:
    driver: bridge
